name: Lint and test charts and code

on:
  pull_request:
    paths:
      - "**"
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "**"

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

  test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true
          cache-dependency-path: go.sum
      - name: Run tests
        run: |
          make integration-test
          make test

  build-docker-image:
    name: Build Multi-Arch Docker Image
    runs-on: ubuntu-latest
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha
            type=ref,event=tag

      - name: Build Docker image and export to local cache
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false
          outputs: type=local,dest=./image-output

      - name: Archive build output
        run: tar -zcf image-output.tar.gz -C ./image-output .

      - name: Upload image build cache artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-build-cache
          path: image-output.tar.gz

  docker-publish:
    name: Publish Docker image
    needs: [golangci, test, build-docker-image]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download image build cache
        uses: actions/download-artifact@v4
        with:
          name: docker-image-build-cache
      - name: Extract build cache
        run: |
          mkdir -p ./image-output
          tar -zxf image-output.tar.gz -C ./image-output

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push multi-arch image from cache
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          tags: ${{ needs.build-docker-image.outputs.image-tags }}
          push: true
          cache-from: type=local,src=./image-output
